### ISSUE TITLE
Right click to cancel premoves.

### ISSUE THREAD

**Issue by Unihedro** [Raptor-Fics-Interface/Raptor#12]
It's a conventional shortcut to cancel premoves as employed by many web interfaces like lichess.org and chess.com.

**Comment by cday-fics** [comment]
Not a bad idea at all. It would be easy to add it to the mouse button configuration preferences. The only thing I am worried about is it getting in the way of dropping moves in examine mode or when playing zh or bug. I will look into finding a good way to implement it.

**Comment by cday-fics** [comment]
It turns out that you can already do this without any changes:
![screen shot 2016-01-09 at 6 03 58 pm](https://cloud.githubusercontent.com/assets/16505202/12218891/4a9b79f2-b6fb-11e5-8c8d-4ed91f91a327.png)

**Comment by cday-fics** [comment]
I decided to set this as the default for right button in 1.0
I also enabed multi premove as default.
