### ISSUE TITLE
Cannot start rc5

### ISSUE THREAD

**Issue by machredsch** [Raptor-Fics-Interface/Raptor#19]
I wanted to update from version below 1.0 to 1.0rc5.
Downloaded 64bit linux package and run raptor via commandline.
I always got: 
"Hauptklasse raptor.updater.UpdateManager konnte nicht gefunden oder geladen werden"
which means "main class...couldn't be found or loaded"

I looked into updater.jar, there is only a META-INF dir, no code, is this correct?

Java Version: Java 8 aka icedtea-3.0.0_pre07

**Comment by cday-fics** [comment]
The updater doesn't really work. updater.jar needs to be removed. Glad you pointed that out I didn't realize it was being built with an empty updater.jar

To run it download the RC5 zip from here: https://github.com/Raptor-Fics-Interface/Raptor/releases/download/1.0rc5/Raptor_v1.0rc5_Linux_x86_64_GTK2.zip

 unzip it then do java -jar Raptor.jar.

Hopefully one of these days I will get around to creating a debian package for it.

**Comment by machredsch** [comment]
Ok thx, "java -jar" was the command, I tried only "java".
Works.
