### ISSUE TITLE
Login stopped by enter key (OSX version)

### ISSUE THREAD

**Issue by wheublein** [Raptor-Fics-Interface/Raptor#20]
When logging in to the FICS server (frechess.org) the login can be interrupted by hitting the enter key. Using a saved user name and password, automatic login not selected, I press enter or click the login button to begin the login process. After the 'connected' line appears in the main screen and before the login is completed, hitting the enter key will cause the username or password to be entered incorrectly, possibly as empty. 

To prevent this, key input should be disabled in the main console until login is completed.

**Comment by cday-fics** [comment]
Agreed, it should be disabled until login is complete or there is a login error  (invalid password or what not). I will look into adding this for 1.0

**Comment by cday-fics** [comment]
Just added this to 1.0 rc6. Closing this issue.
