### ISSUE TITLE
How to get in contact?

### ISSUE THREAD

**Issue by momiki** [Raptor-Fics-Interface/Raptor#29]
How to get in contact with you?
For example: I can do the german localization. Or is it already on its way?

**Comment by gbtami** [comment]
Ceate your local clone of Raptor.
Look into https://github.com/Raptor-Fics-Interface/Raptor/tree/master/raptor/src/raptor/international
Create Messages-de.properties from Messages.en.properties.
Translate.
Send pull request.

**Comment by cday-fics** [comment]
That works or translate Messages.en to messages.de and post it on here and one of the devs will commit it for you. I think there is a small amount of code needed to add it to the combo box when you launch raptor for the first time.
