### ISSUE TITLE
Automatic game analysis?

### ISSUE THREAD

**Issue by CarbonFixer** [Raptor-Fics-Interface/Raptor#30]
I believe this was in older versions of Raptor (but didn't work very well). It is nice to be able to let Stockfish go over the game automatically and find blunders (instances where the score of your chosen move is x points less than the 'best' move). Are there any plans to re-introduce this feature?

**Comment by cday-fics** [comment]
It was added but didn't work well with UCI engines and had a lot of bugs. I agree it would be nice. There use to be bots that did this for you on fics and website where you could submit pgn files and have them do it for you. Maybe the best approach is to add integration to do it with something that already exists.
