### ISSUE TITLE
In the new features you say you can see your best five move in a game. Where is it? I can’t find it. Thanks

### ISSUE THREAD

**Issue by svElysium** [Raptor-Fics-Interface/Raptor#32]

**Comment by cday-fics** [comment]
Observe a game then click on the calculator icon on the toolbar. You will see something like this:
![screen shot 2016-03-06 at 10 45 45 am](https://cloud.githubusercontent.com/assets/16505202/13555215/8ef3fb38-e388-11e5-9047-45c340304bb7.png)

**Comment by svElysium** [comment]
Dear Sir / Madam,
Does this only work for observing, not examining? I can’t use it for my own game?  I thought  I could. When I examine my game(s) I don’t have the calculator. I am using Rapto 1.0 

Thanks for your quick response.

**Comment by cday-fics** [comment]
It works when examining:
![screen shot 2016-03-06 at 12 50 17 pm](https://cloud.githubusercontent.com/assets/16505202/13555878/e27749ac-e399-11e5-82dd-26c2600536d4.png)

You probably removed the toggle chess engine analysis
manually. You can add it back here in preferences:
![screen shot 2016-03-06 at 12 51 31 pm](https://cloud.githubusercontent.com/assets/16505202/13555887/29199ea0-e39a-11e5-855e-1ef2e2e4e062.png)
