### ISSUE TITLE
32bit Linux Version?

### ISSUE THREAD

**Issue by liborty** [Raptor-Fics-Interface/Raptor#33]
Are you planning a 32 bit version, or at least instructions for how to build one?

**Comment by liborty** [comment]
Your 64bit version unsurprisingly does not work on my Intel 32bit quadcore processor.

**Comment by cday-fics** [comment]
No plans to add in 32 bit but you can do it manually. All it really takes is the 32 bit swt jars.

Download the 32 bit (i think the one you want is Linux (x86/GTK+) from here http://download.eclipse.org/eclipse/downloads/drops4/R-4.5-201506032000/#SWT

Create a new folder here raptor/projectFiles/swt called Linux_x86_gtk

Edit /raptor/build.xml and set <property name="swtEnv" value="Linux_x86_gtk" />

'ant run' in the dir raptor should start it

If you want to build a zip you can clone the Linux_x86_64Zip target and tailor it for Linux_x86_gtk. After you run it with 'ant Linux_x86_gtk' the zip will be in raptor/target/install

https://github.com/Raptor-Fics-Interface/Raptor/wiki/How-To-Build-Raptor-from-the-command-line has instructions on how to get setup with command line
