### ISSUE TITLE
How to configure UCI chess engine?

### ISSUE THREAD

**Issue by heuchi** [Raptor-Fics-Interface/Raptor#34]
Hi,
it used to be possible to configure chess engines in Raptor (prior to v1.0), but I can't find this anymore. And currently I've no working engine here. The selector has 'Stockfish6', but when I hit 'Start' nothing happens. I'm on Kubuntu 14.04.

Edit: After I restarted Raptor, the engine now worked. But I would still like to know where I can configure it, because I have a newer version of stockfish and also some other engines, that used to work in Raptor.

**Comment by cday-fics** [comment]
It requires a code change to do this. Update UCIEngineService to point to the new stockfish version you copied over in raptor/projectFiles/${Env}. This works for any UCI engine.

**Comment by heuchi** [comment]
Thanks a lot for the quick response. I'm going to try it.
