### ISSUE TITLE
Bad FEN position sent to stockfish causes engine crash

### ISSUE THREAD

**Issue by dmansfield** [Raptor-Fics-Interface/Raptor#36]
I am examining my last (awful) game on FICS and for some moves, the analysis just won't start.  I debugged the position being sent to the stockfish engine, and it seems the "en passant" square is being sent incorrectly.  In this position: 

> position fen 5rk1/pp1n1pbp/1q2rnp1/2p3B1/P3P3/2N1QB1P/1PP3P1/R4R1K b - a6 0 16

The "en passant" square should have been a3 (not a6).  The previous move was a2a4. 

This happens after all 2-space pawn moves by white in this game.  I was black in this game in case it matters.  

When a bad position is sent, stockfish just exits.

**Comment by cday-fics** [comment]
Good find, and thanks for the details. I will fix this in the next release.
