### ISSUE TITLE
Alternate sound pack

### ISSUE THREAD

**Issue by noah** [Raptor-Fics-Interface/Raptor#37]
I have an alternate sound pack based on http://graywz.deviantart.com/art/Windows-Classic-Sounds-for-XP-183327375

It uses TTS for the spoken messages.

Let me know if you are interested in a contribution - tried contacting you on FICS but your mailbox is full

**Comment by cday-fics** [comment]
That would be great. You can even attach the zip file in a comment if you want to. 

I am swamped at my real job but if you upload it here I will take a look at it and try it out. It just may take me a a month or so before I can actually get around to committing it and adding a way to switch sound packs.

**Comment by noah** [comment]
Here's how you can reproduce what I did:

1. Clone [my repo](http://www.github.com/noah/ms_robot) and copy (or link) the sounds there into `resources/sounds`
2. Unzip the Windows Classic Sounds archive found [here](http://graywz.deviantart.com/art/Windows-Classic-Sounds-for-XP-183327375) into `resources/sounds`
3.  `for x in *.wav; do mv $x $x.old; done`
4. 
```
ln -s Windows Classic/Musica/Musica Asterisk.wav ./gameStart.wav
ln -s Windows Classic/Windows 2000/notify.wav ./notificationArrival.wav
ln -s Windows Classic/Robotz/Robotz Menu Command.wav ./capture.wav
ln -s Windows Classic/Musica/Musica Menu Popup.wav ./alert.wav
ln -s Windows Classic/Windows 2000/chord.wav ./illegalMove.wav
ln -s Windows Classic/Utopia/Utopia Exclamation.WAV ./chat.wav
ln -s Windows Classic/Windows 2000/recycle.wav ./obsGameEnd.wav
ln -s Windows Classic/Windows 2000/tada.wav ./win.wav
ln -s Windows Classic/Utopia/Utopia Recycle.WAV ./lose.wav
ln -s Windows Classic/Utopia/Utopia Close.WAV ./move.wav
```


After you've done all that you will have what I think are slightly more subtle sound effects and more robotic-sounding spoken word cues.

It would be cool if, as you suggested, switching packs was possible.  I think storing each pack in a directory relative to `resources/sounds` would be a quick and dirty way to do it - if you end up committing something, let me know and I can repackage the above.

**Comment by cday-fics** [comment]
Took a look at your repo. The sounds you provided in the repo are fine but I am worried about using the microsoft classic sounds. They don't provide a direct zip and it looks like you have to copy them from a windows installation. I also don't know if they are copyrighted or use an open source license.

**Comment by noah** [comment]
Direct link to sounds is here:
http://orig08.deviantart.net/bea0/f/2010/293/0/d/windows_classic_sounds_for_xp_by_graywz-d315cb3.zip

But if licensing a concern, probably best to avoid distributing them.  If you come up with a way to add custom sounds I can contribute some other packs that are license-neutral.  The default is functional but perhaps not ideal.
