### ISSUE TITLE
Chat feature

### ISSUE THREAD

**Issue by ZnBangash** [Raptor-Fics-Interface/Raptor#42]
Hello there,
First of all thanks for this nice software. Is there an option to have a chat/tell tab when chatting with other players instead of using the “tell” command all the time during gameplay and then typing the player name whom one wants to message.
Thanks

**Comment by cday-fics** [comment]
F9 will automatically type in 'tell x' where x is the last person you told something to

**Comment by ZnBangash** [comment]
Sorry, I am using a Mac, I don’t have F9 button.

**Comment by TheRealCDay** [comment]
you can use '.' to tell the last person who sent you a tell
e.g.:
. test
